FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        username:
            expose: true
        cargoType:
            expose: true
        phone:
            expose: true
        city:
            expose: true
        cityDistrict:
            expose: true
        description:
            expose: true
        dimensions:
            expose: true
        loaders:
            expose: true
        workArea:
            expose: true
        autoType:
            expose: true
        price:
            expose: true
        minHour:
            expose: true
        workTimeSettings:
            expose: true