app_api:
    resource: "@UserBundle/Controller/Api"
    type:     annotation
    prefix:   /api/v1
    defaults:
        _format: json
        
app_base:
    resource: "@UserBundle/Controller/Base"
    type:     annotation
    prefix:   /

app_admin:
    resource: "@UserBundle/Controller/Admin"
    type:     annotation
    prefix:   /admin