# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    cargo_types: [cargo_300, cargo_700, cargo_1500, cargo_3000, cargo_6000, cargo_over_6000]

services:
    token_authenticator:
        class: UserBundle\Security\TokenAuthenticator
        arguments: ['@lexik_jwt_authentication.jwt_encoder', '@doctrine.orm.entity_manager']

    my_user_manager:
        class: UserBundle\Service\MyUserManager
        arguments:
                - '@fos_user.util.password_updater'
                - '@fos_user.util.canonical_fields_updater'
                - '@doctrine.orm.default_entity_manager'
                - '%fos_user.model.user.class%'
    image_carriers_helper:
        class: UserBundle\Helper\UserImageHelper
        arguments:
                - '%kernel.root_dir%/../web/bundles/carriers/'